/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER E5-471
 */
public class quiz1 extends javax.swing.JFrame {

    /**
     * Creates new form quiz1
     */
    public quiz1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        absen = new javax.swing.JLabel();
        matpel = new javax.swing.JLabel();
        nilai = new javax.swing.JLabel();
        TextFieldNama = new javax.swing.JTextField();
        TextFieldAbsen = new javax.swing.JTextField();
        TextFieldMatpel = new javax.swing.JTextField();
        TextFieldNilai = new javax.swing.JTextField();
        buttonProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Penilaian Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(118, 11, 161, 29);

        nama.setText("Nama");
        getContentPane().add(nama);
        nama.setBounds(80, 55, 50, 20);

        absen.setText("Absen");
        getContentPane().add(absen);
        absen.setBounds(80, 93, 50, 20);

        matpel.setText("Matpel");
        getContentPane().add(matpel);
        matpel.setBounds(80, 131, 40, 20);

        nilai.setText("Nilai");
        getContentPane().add(nilai);
        nilai.setBounds(80, 159, 60, 30);

        TextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldNama);
        TextFieldNama.setBounds(188, 48, 161, 30);
        getContentPane().add(TextFieldAbsen);
        TextFieldAbsen.setBounds(188, 86, 161, 30);
        getContentPane().add(TextFieldMatpel);
        TextFieldMatpel.setBounds(188, 124, 161, 30);
        getContentPane().add(TextFieldNilai);
        TextFieldNilai.setBounds(188, 162, 161, 30);

        buttonProses.setText("Proses");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonProses);
        buttonProses.setBounds(178, 203, 65, 30);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(55, 239, 306, 144);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 400);

        setSize(new java.awt.Dimension(416, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNamaActionPerformed

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesActionPerformed
        String nama = TextFieldNama.getText();
        int absen = Integer.parseInt(TextFieldAbsen.getText());
        String matpel = TextFieldMatpel.getText();
        int nilai = Integer.parseInt(TextFieldNilai.getText());
        String predikat="";
        
        if(nilai > 100)
        {
            predikat = "Amazing";
        }else if (nilai >= 86 && nilai == 100)
        {
            predikat = "Sempurna";
        }else if (nilai >= 75 && nilai <= 85)
        {
            predikat = "Lulus";
        }else if (nilai >= 0 && nilai <= 74)
        {
            predikat = "Tidak Lulus";
        }else 
            predikat = "";
        
        TA.setText("Nama : "+nama+"\nAbsen : "+absen+"\nMatpel : "
                + ""+matpel+" \nNilai :"
                        + " "+nilai+"\nKeterangan : "+predikat);
    }//GEN-LAST:event_buttonProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField TextFieldAbsen;
    private javax.swing.JTextField TextFieldMatpel;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldNilai;
    private javax.swing.JLabel absen;
    private javax.swing.JButton buttonProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel matpel;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nilai;
    // End of variables declaration//GEN-END:variables
}
